AWSTemplateFormatVersion: 2010-09-09
Resources:
  BlinkyFrontendBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "bjss-blinky"
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginIdentity}"
            Action: "s3:GetObject"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref BlinkyFrontendBucket
                - /*
      Bucket: !Ref BlinkyFrontendBucket

  CloudFrontOriginIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "origin identity"

  publicDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultRootObject: index.html
        Origins:
          - DomainName: !GetAtt
              - BlinkyFrontendBucket
              - DomainName
            Id: !Ref BlinkyFrontendBucket
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginIdentity}"
        Enabled: "true"
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: !Ref BlinkyFrontendBucket
          ForwardedValues:
            QueryString: "false"
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          CloudFrontDefaultCertificate: "true"
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - publicDistribution
      - DomainName
    Description: URL for website hosted on S3
  CloudFrontID:
    Value: !GetAtt
      - publicDistribution
      - Id
    Description: ID for Cloud Front Distribution
  S3BucketSecureURL:
    Value: !Join
      - ""
      - - "https://"
        - !GetAtt
          - BlinkyFrontendBucket
          - DomainName
    Description: Name of S3 bucket to hold website content
