AWSTemplateFormatVersion: 2010-09-09
Resources:
  BlinkyFrontendBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "bjss-blinky"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref BlinkyFrontendBucket
                - /*
      Bucket: !Ref BlinkyFrontendBucket
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - BlinkyFrontendBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ""
      - - "https://"
        - !GetAtt
          - BlinkyFrontendBucket
          - DomainName
    Description: Name of S3 bucket to hold website content
