/* tslint:disable */
/* eslint-disable */
/**
 * Blinky-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Desk } from './Desk';
import {
    DeskFromJSON,
    DeskFromJSONTyped,
    DeskToJSON,
} from './Desk';

/**
 * 
 * @export
 * @interface AllDesksResponse
 */
export interface AllDesksResponse {
    /**
     * 
     * @type {Array<Desk>}
     * @memberof AllDesksResponse
     */
    desks?: Array<Desk> | null;
}

/**
 * Check if a given object implements the AllDesksResponse interface.
 */
export function instanceOfAllDesksResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AllDesksResponseFromJSON(json: any): AllDesksResponse {
    return AllDesksResponseFromJSONTyped(json, false);
}

export function AllDesksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllDesksResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'desks': !exists(json, 'desks') ? undefined : (json['desks'] === null ? null : (json['desks'] as Array<any>).map(DeskFromJSON)),
    };
}

export function AllDesksResponseToJSON(value?: AllDesksResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'desks': value.desks === undefined ? undefined : (value.desks === null ? null : (value.desks as Array<any>).map(DeskToJSON)),
    };
}

