/* tslint:disable */
/* eslint-disable */
/**
 * Blinky-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Desk
 */
export interface Desk {
    /**
     * 
     * @type {string}
     * @memberof Desk
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Desk
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Desk
     */
    posX: number;
    /**
     * 
     * @type {number}
     * @memberof Desk
     */
    posY: number;
}

/**
 * Check if a given object implements the Desk interface.
 */
export function instanceOfDesk(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "posX" in value;
    isInstance = isInstance && "posY" in value;

    return isInstance;
}

export function DeskFromJSON(json: any): Desk {
    return DeskFromJSONTyped(json, false);
}

export function DeskFromJSONTyped(json: any, ignoreDiscriminator: boolean): Desk {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'posX': json['posX'],
        'posY': json['posY'],
    };
}

export function DeskToJSON(value?: Desk | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'posX': value.posX,
        'posY': value.posY,
    };
}

