/* tslint:disable */
/* eslint-disable */
/**
 * Blinky-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Desk
 */
export interface Desk {
    /**
     * 
     * @type {string}
     * @memberof Desk
     */
    deskId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Desk
     */
    assignedName?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Desk
     */
    isAvailable?: boolean;
}

/**
 * Check if a given object implements the Desk interface.
 */
export function instanceOfDesk(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeskFromJSON(json: any): Desk {
    return DeskFromJSONTyped(json, false);
}

export function DeskFromJSONTyped(json: any, ignoreDiscriminator: boolean): Desk {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deskId': !exists(json, 'deskId') ? undefined : json['deskId'],
        'assignedName': !exists(json, 'assignedName') ? undefined : json['assignedName'],
        'isAvailable': !exists(json, 'isAvailable') ? undefined : json['isAvailable'],
    };
}

export function DeskToJSON(value?: Desk | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deskId': value.deskId,
        'assignedName': value.assignedName,
        'isAvailable': value.isAvailable,
    };
}

