/* tslint:disable */
/* eslint-disable */
/**
 * Blinky-Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Room } from './Room';
import {
    RoomFromJSON,
    RoomFromJSONTyped,
    RoomToJSON,
} from './Room';

/**
 * 
 * @export
 * @interface RoomsResponse
 */
export interface RoomsResponse {
    /**
     * 
     * @type {Array<Room>}
     * @memberof RoomsResponse
     */
    rooms?: Array<Room> | null;
}

/**
 * Check if a given object implements the RoomsResponse interface.
 */
export function instanceOfRoomsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RoomsResponseFromJSON(json: any): RoomsResponse {
    return RoomsResponseFromJSONTyped(json, false);
}

export function RoomsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rooms': !exists(json, 'rooms') ? undefined : (json['rooms'] === null ? null : (json['rooms'] as Array<any>).map(RoomFromJSON)),
    };
}

export function RoomsResponseToJSON(value?: RoomsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rooms': value.rooms === undefined ? undefined : (value.rooms === null ? null : (value.rooms as Array<any>).map(RoomToJSON)),
    };
}

